# Generated by Django 2.0.4 on 2018-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, verbose_name='产品编号')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('image', models.URLField(null=True, verbose_name='图片地址')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
            ],
            options={
                'verbose_name': '产品目录',
                'verbose_name_plural': '产品目录',
            },
        ),
    ]
