# Generated by Django 2.0.4 on 2018-04-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品分类')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, verbose_name='产品编号')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('image', models.URLField(null=True, verbose_name='图片地址')),
                ('website', models.URLField(null=True, verbose_name='产品网址')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='产品分类')),
            ],
        ),
    ]
