# Generated by Django 2.0.4 on 2018-05-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180412_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存数量'),
        ),
    ]
