# Generated by Django 2.0.4 on 2018-05-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180509_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('name', models.CharField(max_length=20, verbose_name='收货人姓名')),
                ('location', models.CharField(max_length=20, verbose_name='收货人地址')),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('item', models.TextField(verbose_name='已购商品')),
                ('date', models.TimeField(verbose_name='下单时间')),
            ],
        ),
    ]
